Repository Jeck0v/Guts, pull requests merged in 2025-07, with the labels that each got.

#34 Feat/commit tree
  Cargo.toml
  flake.lock
  src/cli.rs
  src/commands/cat_file.rs
  src/commands/commit_tree.rs
  src/commands/mod.rs
  src/core/cat.rs
  src/core/object.rs
  src/main.rs
  tests/test_cat_file.rs
  tests/test_commit_tree.rs
Labels: documentation, enhancement

#44 integration of rm commande
  src/cli.rs
  src/commands/mod.rs
  src/commands/rm.rs
  src/core/simple_index.rs
  src/main.rs
  src/terminal/app.rs
Labels: enhancement, Need review

#45 commit + status upgrade + test rework
  Cargo.toml
  src/cli.rs
  src/commands/commit.rs
  src/commands/mod.rs
  src/commands/status.rs
  src/core/repo.rs
  src/core/simple_index.rs
  src/main.rs
  src/terminal/app.rs
  tests/01_plumbing_hash_object.rs
  tests/02_plumbing_cat_file.rs
  tests/03_plumbing_write_tree.rs
  tests/04_plumbing_commit_tree.rs
  tests/05_integration_workflow.rs
  tests/README.md
  tests/manual/01_porcelain_init.rs
  tests/manual/02_porcelain_add.rs
  tests/manual/03_porcelain_commit.rs
Labels: enhancement, Need review

#48 add log commande
  src/cli.rs
  src/commands/log.rs
  src/commands/mod.rs
  src/main.rs
  src/terminal/app.rs
  tests/01_plumbing_hash_object.rs
  tests/05_integration_workflow.rs
  tests/manual/04_porcelain_log.rs
Labels: enhancement, Need review

#60 Refacto tui sys exec
  src/terminal/app.rs
  windows-installer/Guts_Installer.exe
Labels: enhancement

#69 Feat/merge command
  src/cli.rs
  src/commands/cat_file.rs
  src/commands/checkout.rs
  src/commands/commit.rs
  src/commands/commit_tree.rs
  src/commands/log.rs
  src/commands/merge.rs
  src/commands/mod.rs
  src/core/cat.rs
  src/core/object.rs
  src/core/parse_tree.rs
  src/main.rs
  src/terminal/app.rs
Labels: documentation, enhancement
